/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssetDescriptionUpdateManyWithoutTransactionsInput } from "./AssetDescriptionUpdateManyWithoutTransactionsInput";
import {
  ValidateNested,
  IsOptional,
  IsInt,
  IsNumber,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { BlockTransactionUpdateManyWithoutTransactionsInput } from "./BlockTransactionUpdateManyWithoutTransactionsInput";
import { AssetUpdateManyWithoutTransactionsInput } from "./AssetUpdateManyWithoutTransactionsInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class TransactionUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AssetDescriptionUpdateManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => AssetDescriptionUpdateManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => AssetDescriptionUpdateManyWithoutTransactionsInput, {
    nullable: true,
  })
  assetDescriptions?: AssetDescriptionUpdateManyWithoutTransactionsInput;

  @ApiProperty({
    required: false,
    type: () => BlockTransactionUpdateManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => BlockTransactionUpdateManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => BlockTransactionUpdateManyWithoutTransactionsInput, {
    nullable: true,
  })
  blocksTransactions?: BlockTransactionUpdateManyWithoutTransactionsInput;

  @ApiProperty({
    required: false,
    type: () => AssetUpdateManyWithoutTransactionsInput,
  })
  @ValidateNested()
  @Type(() => AssetUpdateManyWithoutTransactionsInput)
  @IsOptional()
  @Field(() => AssetUpdateManyWithoutTransactionsInput, {
    nullable: true,
  })
  createdAssets?: AssetUpdateManyWithoutTransactionsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  expiration?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  fee?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hash?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  networkVersion?: number;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  notes?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  size?: number;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  spends?: InputJsonValue;
}

export { TransactionUpdateInput as TransactionUpdateInput };
