/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsInt,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { AssetDescriptionUpdateManyWithoutAssetsInput } from "./AssetDescriptionUpdateManyWithoutAssetsInput";
import { GraphQLBigInt } from "../../util/GraphQLBigInt";

@InputType()
class AssetUpdateInput {
  @ApiProperty({
    required: false,
    type: () => TransactionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TransactionWhereUniqueInput)
  @IsOptional()
  @Field(() => TransactionWhereUniqueInput, {
    nullable: true,
  })
  createdTransaction?: TransactionWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AssetDescriptionUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AssetDescriptionUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AssetDescriptionUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  descriptions?: AssetDescriptionUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  identifier?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metadata?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  owner?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => GraphQLBigInt, {
    nullable: true,
  })
  supply?: bigint;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  verifiedAt?: Date | null;
}

export { AssetUpdateInput as AssetUpdateInput };
