/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BlockService } from "../block.service";
import { BlockCreateInput } from "./BlockCreateInput";
import { BlockWhereInput } from "./BlockWhereInput";
import { BlockWhereUniqueInput } from "./BlockWhereUniqueInput";
import { BlockFindManyArgs } from "./BlockFindManyArgs";
import { BlockUpdateInput } from "./BlockUpdateInput";
import { Block } from "./Block";
import { BlockTransactionFindManyArgs } from "../../blockTransaction/base/BlockTransactionFindManyArgs";
import { BlockTransaction } from "../../blockTransaction/base/BlockTransaction";
import { BlockTransactionWhereUniqueInput } from "../../blockTransaction/base/BlockTransactionWhereUniqueInput";

export class BlockControllerBase {
  constructor(protected readonly service: BlockService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Block })
  async create(@common.Body() data: BlockCreateInput): Promise<Block> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        difficulty: true,
        graffiti: true,
        hash: true,
        id: true,
        main: true,
        networkVersion: true,
        previousBlockHash: true,
        sequence: true,
        size: true,
        timeSinceLastBlockMs: true,
        timestamp: true,
        transactionsCount: true,
        updatedAt: true,
        work: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Block] })
  @ApiNestedQuery(BlockFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Block[]> {
    const args = plainToClass(BlockFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        difficulty: true,
        graffiti: true,
        hash: true,
        id: true,
        main: true,
        networkVersion: true,
        previousBlockHash: true,
        sequence: true,
        size: true,
        timeSinceLastBlockMs: true,
        timestamp: true,
        transactionsCount: true,
        updatedAt: true,
        work: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Block })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: BlockWhereUniqueInput
  ): Promise<Block | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        difficulty: true,
        graffiti: true,
        hash: true,
        id: true,
        main: true,
        networkVersion: true,
        previousBlockHash: true,
        sequence: true,
        size: true,
        timeSinceLastBlockMs: true,
        timestamp: true,
        transactionsCount: true,
        updatedAt: true,
        work: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Block })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: BlockWhereUniqueInput,
    @common.Body() data: BlockUpdateInput
  ): Promise<Block | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          difficulty: true,
          graffiti: true,
          hash: true,
          id: true,
          main: true,
          networkVersion: true,
          previousBlockHash: true,
          sequence: true,
          size: true,
          timeSinceLastBlockMs: true,
          timestamp: true,
          transactionsCount: true,
          updatedAt: true,
          work: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Block })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: BlockWhereUniqueInput
  ): Promise<Block | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          difficulty: true,
          graffiti: true,
          hash: true,
          id: true,
          main: true,
          networkVersion: true,
          previousBlockHash: true,
          sequence: true,
          size: true,
          timeSinceLastBlockMs: true,
          timestamp: true,
          transactionsCount: true,
          updatedAt: true,
          work: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/blocksTransactions")
  @ApiNestedQuery(BlockTransactionFindManyArgs)
  async findManyBlocksTransactions(
    @common.Req() request: Request,
    @common.Param() params: BlockWhereUniqueInput
  ): Promise<BlockTransaction[]> {
    const query = plainToClass(BlockTransactionFindManyArgs, request.query);
    const results = await this.service.findBlocksTransactions(params.id, {
      ...query,
      select: {
        block: {
          select: {
            id: true,
          },
        },

        id: true,
        index: true,

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/blocksTransactions")
  async connectBlocksTransactions(
    @common.Param() params: BlockWhereUniqueInput,
    @common.Body() body: BlockTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      blocksTransactions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/blocksTransactions")
  async updateBlocksTransactions(
    @common.Param() params: BlockWhereUniqueInput,
    @common.Body() body: BlockTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      blocksTransactions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/blocksTransactions")
  async disconnectBlocksTransactions(
    @common.Param() params: BlockWhereUniqueInput,
    @common.Body() body: BlockTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      blocksTransactions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
